# Generated by Django 4.1.1 on 2023-03-13 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='videoAns',
            fields=[
                ('ansId', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('assessment_name', models.CharField(max_length=300, null=True)),
                ('videoAns', models.FileField(blank=True, upload_to='media')),
                ('trasnscript', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
